Derive all other derivable traits
magiclen/cidr-utils pull request #3
Opened 2020-02-17 15:03 UTC by nabijaczleweli

In my use-case I need to stuff these into `BTreeMap<>`s, and that was foiled by no `Hash` impls.

This PR gratuitously implements all traits for all structs in `cidr`.

2021-07-11 11:00 UTC, Skarlett approved these changes

2023-03-02 00:14 UTC, robjtede requested changes

2023-03-02 00:14 UTC, robjtede commented on src/cidr/ipv4_cidr.rs
> +#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Copy, Clone, Hash)]
I disagree with implementing Copy, Eq, PartialOrd, Ord, and Hash on the error types.

2023-03-02 00:14 UTC, robjtede commented on src/cidr/ipv4_cidr.rs
> +#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Copy, Clone, Hash)]
I disagree with deriving PartialEq, Eq, PartialOrd, Ord, Copy, and Hash on the iterator types.

2023-03-02 01:37 UTC, nabijaczleweli commented
And I don't care anymore and the rebase looks hellish

2023-03-02 01:37 UTC, closed without merging